In [1]:
#import packages
import pandas as pd
import numpy as np

#to plot within notebook
import matplotlib.pyplot as plt

#importing required libraries
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM
from keras.models import model_from_json


#setting figure size
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 20,200

#for normalizing data
from sklearn.preprocessing import MinMaxScaler

In [54]:
df = pd.read_csv('data.csv')

In [56]:
for col in df.columns:
    df[col] = [str(x).split("'")[1] for x in df[col]]
    df=df.rename(columns={col:str(col).split("'")[1]})

In [57]:
df

,date,buy,sell,low,high,last,vol
0,2021-10-30 00:47:48,4898463.0,4899999.0,4762003.0,4949000.0,4910491.0,456.09217
1,2021-10-30 00:47:53,4890424.0,4899999.0,4762003.0,4949000.0,4890424.0,456.09217
2,2021-10-30 00:47:48,4898463.0,4899999.0,4762003.0,4949000.0,4910491.0,456.09217
3,2021-10-30 00:47:53,4890424.0,4899999.0,4762003.0,4949000.0,4890424.0,456.09217
4,2021-10-30 00:47:58,4890426.0,4910489.0,4762003.0,4949000.0,4910490.0,456.09217
5,2021-10-30 00:47:53,4890424.0,4899999.0,4762003.0,4949000.0,4890424.0,456.09217
6,2021-10-30 00:47:58,4890426.0,4910489.0,4762003.0,4949000.0,4910490.0,456.09217
7,2021-10-30 00:48:03,4898600.0,4899999.0,4762003.0,4949000.0,4910490.0,456.09217
8,2021-10-30 00:47:58,4890426.0,4910489.0,4762003.0,4949000.0,4910490.0,456.09217
9,2021-10-30 00:48:03,4898600.0,4899999.0,4762003.0,4949000.0,4910490.0,456.09217
10,2021-10-30 00:48:08,4898600.0,4910485.0,4762956.0,4949000.0,4910485.0,456.09217
11,2021-10-30 00:48:03,4898600.0,4899999.0,4762003.0,4949000.0,4910490.0,456.09217
12,2021-10-30 00:48:08,4898600.0,4910485.0,4762956.0,4949000.0,4910485.0,456.09217
13,2021-10-30 00:48:13,4898601.0,4910483.0,4762956.0,4949000.0,4898601.0,456.09217
14,2021-10-30 00:48:08,4898600.0,4910485.0,4762956.0,4949000.0,4910485.0,456.09217
15,2021-10-30 00:48:13,4898601.0,4910483.0,4762956.0,4949000.0,4898601.0,456.09217
16,2021-10-30 00:48:17,4898601.0,4910481.0,4762956.0,4949000.0,4910481.0,456.09217
17,2021-10-30 00:48:13,4898601.0,4910483.0,4762956.0,4949000.0,4898601.0,456.09217
18,2021-10-30 00:48:17,4898601.0,4910481.0,4762956.0,4949000.0,4910481.0,456.09217
19,2021-10-30 00:48:22,4898601.0,4910479.0,4762956.0,4949000.0,4910481.0,456.09217
20,2021-10-30 00:48:17,4898601.0,4910481.0,4762956.0,4949000.0,4910481.0,456.09217
21,2021-10-30 00:48:22,4898601.0,4910479.0,4762956.0,4949000.0,4910481.0,456.09217
22,2021-10-30 00:48:27,4901788.0,4910478.0,4762956.0,4949000.0,4910481.0,456.09217
23,2021-10-30 00:48:22,4898601.0,4910479.0,4762956.0,4949000.0,4910481.0,456.09217
24,2021-10-30 00:48:27,4901788.0,4910478.0,4762956.0,4949000.0,4910481.0,456.09217
25,2021-10-30 00:48:32,4901788.0,4910491.0,4762956.0,4949000.0,4910481.0,456.09217
26,2021-10-30 00:48:27,4901788.0,4910478.0,4762956.0,4949000.0,4910481.0,456.09217
27,2021-10-30 00:48:32,4901788.0,4910491.0,4762956.0,4949000.0,4910481.0,456.09217
28,2021-10-30 00:48:37,4898605.0,4901788.0,4762956.0,4949000.0,4898604.0,456.09217
29,2021-10-30 00:48:42,4898600.0,4901788.0,4762956.0,4949000.0,4898604.0,456.09217
30,2021-10-30 00:48:47,4898604.0,4901788.0,4762956.0,4949000.0,4901788.0,456.09217
31,2021-10-30 00:48:42,4898600.0,4901788.0,4762956.0,4949000.0,4898604.0,456.09217
32,2021-10-30 00:48:47,4898604.0,4901788.0,4762956.0,4949000.0,4901788.0,456.09217
33,2021-10-30 00:48:51,4898604.0,4898605.0,4762956.0,4949000.0,4909984.0,456.09217
34,2021-10-30 00:48:47,4898604.0,4901788.0,4762956.0,4949000.0,4901788.0,456.09217
35,2021-10-30 00:48:51,4898604.0,4898605.0,4762956.0,4949000.0,4909984.0,456.09217